- name: upload the netdataDeploy script
  become: yes
  copy:
    src: ./netdataDeploy.sh
    dest: /home/ubuntu/
    mode: 0777

- name: execute the netdataDeploy script
  become: yes
  shell: /home/ubuntu/netdataDeploy.sh