- name: upload the setCouchDB script
  become: yes
  copy:
    src: ./setCouchDB.sh
    dest: /home/ubuntu/
    mode: 0777

- name: execute the setCouchDB script
  become: yes
  shell: /home/ubuntu/setCouchDB.sh