---

# add proxy
- name: Add proxy in /etc/environment
  become: yes
  blockinfile:
    path: /etc/environment
    block: |
      HTTP_PROXY={{HTTP_PROXY}}
      HTTPS_PROXY={{HTTPS_PROXY}}
      http_proxy={{http_proxy}}
      https_proxy={{https_proxy}}
      no_proxy={{no_proxy}}

# reboot vm
- name: Reboot a machine
  become: yes
  reboot:
    reboot_timeout: 3000