- name: upload the nginx_frontend script
  become: yes
  copy:
    src: ./nginx_frontend.sh
    dest: /home/ubuntu/
    mode: 0777

- name: execute the nginx_frontend script
  become: yes
  shell: /home/ubuntu/nginx_frontend.sh