- hosts: all
  vars_files:
    - host_vars/remote.yaml
  gather_facts: true

  roles:
    - role: netdata-instance-visualization

- hosts: masternode
  vars_files:
    - host_vars/remote.yaml
  gather_facts: true

  roles:
    - role: MapReduce_Setting

- hosts: redisCluster
  vars_files:
    - host_vars/remote.yaml
  gather_facts: true

  roles:
    - redis-cluster

- hosts: backend
  vars_files:
    - host_vars/remote.yaml
  gather_facts: true

  roles:
    - backend

- hosts: instance1
  vars_files:
    - host_vars/remote.yaml
  gather_facts: true

  roles:
    - nginx-frontend